---

- hosts: SWITCHES
  gather_facts: no
  
  tasks:

## Set the Boot Variable on a Cisco 9000 series xe switch
    - name: Set Boot Variable
      ios_config:
        commands:
          - 'boot system flash:packages.conf'
        save_when: always
