---

- hosts: SWITCHES
  gather_facts: no
  
  tasks:

## Install image to flash on a Cisco 9000 series xe switch
    - name: Install Image to Flash
      cli_command:
        command: install add file flash:cat9k_lite_iosxe.16.12.07.SPA.bin activate commit
        prompt: This operation may require a reload of the system. Do you want to proceed? 
        answer: y
