---

#################### Backup the device  ######################################

## Create directory on the localhost to save backups in
- hosts: localhost

  tasks:
   - name: Get ansible date/time facts
     setup:
       filter: "ansible_date_time"
       gather_subset: "!all"

   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{hostvars.localhost.DTG}}
     file:
      path: ~/backups/{{hostvars.localhost.DTG}}
      state: directory
  run_once: true
