---

- hosts: SWITCHES
  gather_facts: no
  vars:
    desired_ios_version: 16.12.07
    #upgrade_ios_filename: "cat9k_lite_iosxe.17.06.05.SPA.bin"
    upgrade_ios_filename: "cat9k_lite_iosxe.16.12.07.SPA.bin"
    #upgrade_ios_md5_17_6_5: "77f9504141dad5db1aef7c355051254b"
    upgrade_ios_md5_16_12_7: "ce156add262f1d4a0c798a13aa75672c"
    
  tasks:

## Copy software to target device
    - name: Copy Image // This could take up to 60 minutes
      ansible.netcommon.net_put:
      
        src: ~/Downloads/{{upgrade_ios_filename}}
        dest: flash:/{{upgrade_ios_filename}}
      vars:
        ansible_command_timeout: 19000
        ansible_network_cli_ssh_type: paramiko
        protocol: scp
        ansible_python_interpreter: /usr/bin/python3.10
