---
# Ansible Playbook to upgrade Cisco IOS

- name: Upgrade CISCO IOS
  hosts: sw1

  vars:
    upgrade_ios_version: 17.06.05
    upgrade_ios_filename: "cat9k_lite_iosxe.17.06.05.SPA.bin"
    upgrade_ios_md5: "77f9504141dad5db1aef7c355051254b"
    #upgrade_ios_md5: "77f9504141dad5db1aef7c3550512777"

  tasks:
    - name: CHECK CURRENT VERSION
      ios_facts:
      vars:
        #ansible_command_timeout: 1200

    - debug:
        msg:
          - "Current version is {{ ansible_net_version }}"
          - "Upgrade image is 17.06.05"
            
    - debug:
        msg:
          - "Image is not compliant and will be upgraded"

      when: ansible_net_version != upgrade_ios_version




## Copy software to target device

     - name: Copy Image // This could take up to 10 minutes
       ansible.netcommon.net_put:
        
         src: cat9k_lite_iosxe.17.06.05.SPA.bin
         dest: flash:/cat9k_lite_iosxe.17.06.05.SPA.bin
       vars:
         ansible_command_timeout: 19000
         ansible_network_cli_ssh_type: paramiko
         protocol: scp
         ansible_python_interpreter: /usr/bin/python3.10

## Check MD5 Hash
    - name: Check MD5 Hash
      ios_command:
        commands:
          - command: "verify /md5 flash:{{upgrade_ios_filename}} {{ upgrade_ios_md5}}"
      register: md5_result
      vars:
        ansible_command_timeout: 420

## Change the boot variable to the new image
#    - name: Change Boot Variable to new image
#      ios_config:
#        commands:
#          - "boot system flash:cat9k_lite_iosxe.17.06.05.SPA.bin"
#        save_when: always

## Reload the device
    - name: Reload the Device
      cli_command:
        command: reload
        prompt:
          - confirm
        answer:
          - 'y'

## Wait for Reachability to the device
    - name: Wait for device to come back online
      wait_for:
        host: "{{ inventory_hostname }}"
        #port: 22
        delay: 10
      #delegate_to: localhost

## Check current image

    - name: Check Image version
      ios_facts:

    - debug:
        msg:
          - "Current version is {{ ansible_net_version }}"

    - name: ASSERT THAT THE IOS VERSION IS CORRECT

      #vars:
      #  upgrade_ios_version: 17.06.03

      assert:
        that:
          - upgrade_ios_version == ansible_net_version
        fail_msg: 
          - "The desired upgrade version is: {{upgrade_ios_version}} The current version is: {{ansible_net_version}}"
          - "Upgrade FAILED"
        success_msg: "IOS upgrade has been SUCCESSFULLY completed"
    




